MA-22806-2 Add format_mod_static_table rule in Android.bp
Meet below compile error on android:
fatal error: 'generated_static_table_fourcc.h' file not found

Below commit add a rule format_mod_static_table to use gen_table_fourcc.py
generate generated_static_table_fourcc.h based on include/drm/drm_fourcc.h.
67e9119 Marius Vlad xf86drm: Add a human readable representation for format modifiers

Here add corresponding rule in Android.bp.

Change-Id: I8963947fca2842b5a41b94bb970a3fb5c61518dd
Signed-off-by: Jessie Hao <juan.hao@nxp.com>
(cherry picked from commit 44593f485d2b4223a0f5cb932fe2607e10bbba34)
(cherry picked from commit 3c682629398fd6ee702be9941758d44299a3280a)
Signed-off-by: Jessie Hao <juan.hao@nxp.com>