MA-22806 remove unused Android.bp files to avoid compile errors.
Meet the below compile errors:
error: external/libdrm/radeon/Android.bp:12:1: module "libdrm_radeon"
already defined
       vendor/nxp-opensource/libdrm-imx/radeon/Android.bp:3:1 <--
previous definition here
error: external/libdrm/amdgpu/Android.bp:12:1: module "libdrm_amdgpu"
already defined
       vendor/nxp-opensource/libdrm-imx/amdgpu/Android.bp:3:1 <--
previous definition here

Here just removed all unused Android.bp to avoid redefinition check
error with the below command:
rm -rf `find  -mindepth 2 -name Android.bp`

Change-Id: I9e3a9e9a9581322b28669c004b39f0dc615652c5
Signed-off-by: Jessie Hao <juan.hao@nxp.com>