MA-22132 Fix intel_chipset.c not exist caused android compile error.
Meet the below compile error in android:
error: vendor/nxp-opensource/libdrm-imx/intel/Android.bp:17:1: module
"libdrm_android_intel" variant
"android_vendor.34_arm64_armv8-a_cortex-a53_shared": module source path
"vendor/nxp-opensource/libdrm-imx/intel/intel_chipset.c" does not exist

As intel/intel_chipset.c not exist, here remove intel/Android.bp
directly to avoid android soong compile check.

Signed-off-by: Jessie Hao <juan.hao@nxp.com>